apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
    - name: demo
      image: tutum/curl
      command: ["/bin/sleep", "infinity"]
      imagePullPolicy: IfNotPresent
      resources:
          limits:
            memory: "64Mi"
            cpu: "100m"    
