---
apiVersion: v1
kind: Pod
metadata:
  name: WEBHOOK_APP
  labels:
    app: WEBHOOK_APP
spec:
  containers:
    - name: WEBHOOK_APP
      image: nsubrahm/webhook-server:0.0.0
      imagePullPolicy: Always
      volumeMounts:
        - name: certs
          mountPath: /etc/certs
          readOnly: true
      ports:
        - containerPort: 4443
          protocol: TCP
      resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
  volumes:
    - name: certs
      secret:
        secretName: WEBHOOK_APP-cert-tls-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: WEBHOOK_APP
spec:
  type: ClusterIP
  ports:
    - name: 4443-tcp
      protocol: TCP
      port: 443
      targetPort: 4443
  selector:
    app: WEBHOOK_APP 