---
apiVersion: v1
kind: Pod
metadata:
  name: ${APP}
  labels:
    app: ${APP}
spec:
  containers:
    - name: ${APP}
      image: ${DOCKER_REPO_NAME}/${WEBHOOK_APP}:0.0.0
      imagePullPolicy: Always
      volumeMounts:
        - name: certs
          mountPath: /etc/certs
          readOnly: true
      ports:
        - containerPort: 4443
          protocol: TCP
  volumes:
    - name: certs
      secret:
        secretName: ${APP}-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP}
spec:
  type: ClusterIP
  ports:
    - name: 4443-tcp
      protocol: TCP
      port: 443
      targetPort: 4443
  selector:
    app: ${APP} 